language: php

sudo: false

dist: trusty

cache:
  directories:
    - $HOME/.composer/cache

addons:
  apt:
    packages:
      - parallel

php:
  - 7.0
  - 7.1
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_script:
    - flags="--prefer-dist"
    - composer install $flags
    - bin/composer install $flags
    - git config --global user.name travis-ci
    - git config --global user.email travis@example.com

script:
    - ls -d test/* | parallel --gnu --keep-order 'echo "Running {} tests"; ./vendor/bin/phpunit -c tests/complete.phpunit.xml --colors=always {} || (echo -e "\e[41mFAILED\e[0m {}" && $(exit 1));'

git:
  depth: 3
  submodules: false
