language: php

sudo: false

dist: xenial

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.3
    - php: nightly

before_install:
  - composer self-update
  - composer clear-cache
  
install: true

before_script:
  - travis_retry composer update --no-interaction --no-ansi --no-progress --no-suggest --optimize-autoloader --prefer-stable
  - git config --global user.name travis-ci
  - git config --global user.email travis@example.com
  # install ethereum so we can compile .sol files with solc
  - sudo add-apt-repository ppa:ethereum/ethereum -y
  - sudo apt-get update
  - sudo apt-get install -y solc geth

script:
  # todo: generate a deploy script that includes setting binarys to 755
  - chmod 755 src/Bigprimes/bin/factors
  - ./vendor/bin/phpunit --coverage-clover=coverage.xml
  - echo "Running {} tests"; ./vendor/bin/phpunit -c phpunit.xml --testsuite tests --colors=always || (echo -e "\e[41mFAILED\e[0m {}" && $(exit 1));
  # check we can compile our ethereum contracts
  - solc contracts/33.sol
  # deploy the compiled contract
  # TODO: Only deploy on change to solc output
  - chmod +x ./contracts/deploy-rinkeby.sh && ./contracts/deploy-rinkeby.sh

git:
  depth: 3
  submodules: false

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
