---
AWSTemplateFormatVersion: '2010-09-09'
Description: Generate bigprimes api gateway.
Parameters:
  certificateARN:
    Description: certificate for bigprimes.net
    Type: String
Resources:
  PHPLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:invokeFunction
      FunctionName:
        Fn::GetAtt:
        - BTCLambda
        - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
        - ''
        - - 'arn:aws:execute-api:'
          - Ref: AWS::Region
          - ":"
          - Ref: AWS::AccountId
          - ":"
          - Ref: RaiAPI
          - "/*"
  UsagePlan:
    Type: "AWS::ApiGateway::UsagePlan"
    Properties:
      Description: "Rai"
      Quota:
        Limit: 5000
        Period: MONTH
      Throttle:
        BurstLimit: 5
        RateLimit: 2
      UsagePlanName: UsagePlan
            
  BigPrimesAPI:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: Rai API
      Description: API used for Rai
      FailOnWarnings: true
          
  ApiStage:
    DependsOn:
    - ApiGatewayAccount
    Type: AWS::ApiGateway::Stage
    Properties:
      DeploymentId:
        Ref: ApiDeployment
      MethodSettings:
      - DataTraceEnabled: true
        HttpMethod: "*"
        LoggingLevel: INFO
        ResourcePath: "/*"
      RestApiId:
        Ref: RaiAPI
      StageName: LATEST
      
  ApiGatewayCloudWatchLogsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - apigateway.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
      - PolicyName: ApiGatewayLogsPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:DescribeLogGroups
            - logs:DescribeLogStreams
            - logs:PutLogEvents
            - logs:GetLogEvents
            - logs:FilterLogEvents
            Resource: "*"
            
  ApiGatewayAccount:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn:
        Fn::GetAtt:
        - ApiGatewayCloudWatchLogsRole
        - Arn
        
  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
    - LSRequest
    Properties:
      RestApiId:
        Ref: RaiAPI
      StageName: DummyStage
      
  DomainName:
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName: api.rai.mayhew.io
      CertificateArn: !Ref certificateARN
      
  DomainMapping:
    Type: 'AWS::ApiGateway::BasePathMapping'
    Properties:
      BasePath: ""
      DomainName: !Ref DomainName
      RestApiId: !Ref RaiAPI
      
  APIDNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: mayhew.io.
      Comment: RAI API
      Name: "api.rai.mayhew.io"
      Type: CNAME
      TTL: '300'
      ResourceRecords:
      - Fn::Join:
        - ''
        - - Ref: RaiAPI
          - ".execute-api."
          - Ref: AWS::Region
          - ".amazonaws.com."

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: root
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:*
            Resource: arn:aws:logs:*:*:*
